# Generated by Django 3.2.12 on 2022-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('membership_type', models.CharField(choices=[('RE', 'Religious'), ('SE', 'Secular Clergy'), ('LP', 'Lay Person')], max_length=2)),
            ],
        ),
    ]
